# Generated by Django 5.0.6 on 2024-06-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_options_alter_posts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, unique_for_date='date_publish', verbose_name='Слаг'),
        ),
    ]
