# Generated by Django 5.0.6 on 2024-06-22 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comment_options_alter_comment_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
