# Generated by Django 5.0.6 on 2024-08-22 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-created_timestamp'], 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
    ]
