# Generated by Django 5.0.6 on 2024-05-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_birth',
            field=models.DateTimeField(blank=True, default=None, verbose_name='Дата рождения'),
        ),
    ]
