# Generated by Django 5.0.6 on 2024-07-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_date_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subs_news',
            field=models.BooleanField(choices=[(True, 'Подписан(-а)'), (False, 'Не подписан(-а)')], default=1, verbose_name='Подписка на рассылку'),
        ),
    ]
