# Generated by Django 5.0.6 on 2024-07-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_date_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='users/photo/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
