# Generated by Django 5.0.6 on 2024-08-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_delivery',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес доставки'),
        ),
    ]
